### PR TITLE
Set up rspec

### PR DESCRIPTION
**Pull request by vbrazo**
@neenus The goal of this PR is to set up [`rspec`](http://rspec.info/) and add the first tests for the models.

I wrote a few tests to show you how we test the `associations` and `validations`. I'm using [`shoulda-matchers`](https://github.com/thoughtbot/shoulda-matchers). Could you add the other missing tests for the models? 

I think you can merge this PR and create a new one with your changes.

** I'm not sure how familiar you're with `rspec`. After bundling this PR, you should be able to run the tests with the following command: `bundle exec rspec`.

### CODE REVIEW

**Comment by vbrazo** [comment]
If you want to have this project in your portfolio, you need to add tests. Tests are super important. If you're not familiar with them, you'll get familiar. I'll review your commits to make sure that you're doing a good job. 

Let's add the missing tests for the models first, then we can go and add the missing controller tests and UI tests. How does that sound to you? @neenus

**Comment by neenus** [comment]
Thanks @vbrazo ... I will be going over the tests you included and create more for each model.

**Comment by vbrazo** [comment]
Glad to see that you'll write these specs. Let me know when they're done.

Feel free to schedule a new call with me in case you have doubts about `rspec` or want to learn something more specific.

**Comment by vbrazo** [comment]
Please start using Git branches. I'm not sure how familiar you're with git, but here are a few instructions that you could use in your terminal:

- show the branches in your machine: `git branch`
- create a new branch: `git checkout -b name-of-your-branch`
- delete a branch: `git branch -D name-of-your-branch`
- rename your branch: `git branch -m old-name new-name`
- if you are in a branch and want to push the code: `git push origin name-of-your-branch`
After pushing the code, you come to Github and open a new PR. You can merge the PR through the platform.

PRs are extremely important to keep the code organized. If you are working with a lot of developers simultaneously, you need to use PRs otherwise the development process with master will be tough. This is something that companies may evaluate in your coding challenges. 

p.s: If you're working on a project alone, it's okay. You can commit in the master branch, but keep this piece of advice in mind. You better open a new PR for a new feature. If you're just changing the `README.md` you may not need a PR for that.

Let me know if you need help with GitHub too. I can show you a lot of things in a call.

**Comment by vbrazo** [comment]
I've just noticed that you guys are missing controller tests. I'm going to open a new PR with some examples, and I'll ask you to write the other missing tests. Cheers.

**Pull request merged**
